version: 2.1

jobs:
  solidity:
    docker:
      - image: cimg/node:lts
    parallelism: 10
    resource_class: large
    steps:
      - checkout
      - run: npm ci
      - run: npx hardhat compile
      - run: npx hardhat test
      - run: npm run lint

workflows:
  build_and_test:
    jobs:
      - solidity:
          filters:
            tags:
              only: /.*/